[project]
name = "datarobot-agents-templates"
version = "11.3.4"
description = """
This is a template for DataRobot Agents.
"""
requires-python = ">=3.10"

dependencies = [
    "dotenv>=0.9.9",
    "pytest>=8.4.2",
    "requests>=2.32.5",
    "ruff>=0.14.0",
]
